### ISSUE TITLE
Słaba strona

### ISSUE THREAD

**Issue by S4vyss** [rafal06/car-navigation-site#1]
Responsywność na urządzenia mobilne nie istnieje, prawie zamówiłem produkt ponieważ nie widzi

**Comment by S4vyss** [comment]
dfadfadfadfasdf

**Comment by S4vyss** [comment]
afdfasdfasdfadfasdfa

**Comment by rafal06** [comment]
> Responsywność na urządzenia mobilne nie istnieje, prawie zamówiłem produkt ponieważ nie widzi

Strona nawet nie jest skończona. Jeszcze się nie zabrałem za responsywność.
